# -*- coding: utf-8 -*-
"""HW10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LPr-SXWxKUlWrLJUU9HGxJ7LzC_MkDFQ
"""



import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

data.loc[data['whoAmI'] == 'robot', 'robot'] = True
data.loc[data['whoAmI'] == 'human', 'robot'] = False
data.loc[data['whoAmI'] == 'human', 'human'] = True
data.loc[data['whoAmI'] == 'robot', 'human'] = False
data